.TH m 1 m\-0.0.1
.SH NAME
.B m \- mark arbitrary text to be recalled later by name
.SH SYNOPSIS
.B m [mark\-name] text 
.SH DESCRIPTION
.B m
saves arbitrary text to be recalled later by 
.B mo
(1).
A single non\-option argument is taken as
text to be assigned to the default mark.
If there are multiple non\-option arguments,
the first is taken as the name of a mark,
the rest as text.
.SH OPTIONS
None.
.SH SEE ALSO
.B mo
(1) 
.B mpwd
(1) 
.B vm
(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2010, 2013 Noah Birnel
You may use this software however you like.
