.TH mo 1 mo\-0.0.1
.SH NAME
.B mo \- mark out
.SH SYNOPSIS
.B mo [mark\-name]
.SH DESCRIPTION
.B mo
recalls text previously saved by 
.B m
(1).
When called with no arguments,
.B mo
prints the default mark.
Otherwise,
it prints the mark named on the command line.
.SH OPTIONS
None.
.SH SEE ALSO
.B m
(1) 
.B mpwd
(1) 
.B vm
(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2010, 2013, 2018 Noah Birnel
You may use this software however you like.
