.TH mpwd 1 mpwd\-0.0.1
.SH NAME
.B mpwd \- mark directory 
.SH SYNOPSIS
.B mpwd
[mark\-name]
.SH DESCRIPTION
.B mpwd
is a wrapper script for m.
It saves the current working directory to an 
.B m
(1) mark.
.SH OPTIONS
None.
.SH SEE ALSO
.B m
(1) 
.B mo
(1) 
.B vm
(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2010, 2013 Noah Birnel
You may use this software however you like.
