.TH vm 1 vm\-0.0.1
.SH NAME
.B vm \- view mark
.SH SYNOPSIS
.B vm
.SH DESCRIPTION
.B vm
displays all marks and text previously saved by 
.B m
(1).
.SH OPTIONS
None.
.SH SEE ALSO
.B m
(1) 
.B mpwd
(1) 
.B mo
(1)
.SH BUGS
Probably.
.SH LICENSE
\(co 2010, 2013, 2018 Noah Birnel
You may use this software however you like.
